package com.lxc.myemail.model;

import java.util.ArrayList;
import java.util.List;

public class EmailAccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    public EmailAccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEmailIdIsNull() {
            addCriterion("email_id is null");
            return (Criteria) this;
        }

        public Criteria andEmailIdIsNotNull() {
            addCriterion("email_id is not null");
            return (Criteria) this;
        }

        public Criteria andEmailIdEqualTo(Integer value) {
            addCriterion("email_id =", value, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdNotEqualTo(Integer value) {
            addCriterion("email_id <>", value, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdGreaterThan(Integer value) {
            addCriterion("email_id >", value, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("email_id >=", value, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdLessThan(Integer value) {
            addCriterion("email_id <", value, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdLessThanOrEqualTo(Integer value) {
            addCriterion("email_id <=", value, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdIn(List<Integer> values) {
            addCriterion("email_id in", values, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdNotIn(List<Integer> values) {
            addCriterion("email_id not in", values, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdBetween(Integer value1, Integer value2) {
            addCriterion("email_id between", value1, value2, "emailId");
            return (Criteria) this;
        }

        public Criteria andEmailIdNotBetween(Integer value1, Integer value2) {
            addCriterion("email_id not between", value1, value2, "emailId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andEmailAddressIsNull() {
            addCriterion("email_address is null");
            return (Criteria) this;
        }

        public Criteria andEmailAddressIsNotNull() {
            addCriterion("email_address is not null");
            return (Criteria) this;
        }

        public Criteria andEmailAddressEqualTo(String value) {
            addCriterion("email_address =", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressNotEqualTo(String value) {
            addCriterion("email_address <>", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressGreaterThan(String value) {
            addCriterion("email_address >", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressGreaterThanOrEqualTo(String value) {
            addCriterion("email_address >=", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressLessThan(String value) {
            addCriterion("email_address <", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressLessThanOrEqualTo(String value) {
            addCriterion("email_address <=", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressLike(String value) {
            addCriterion("email_address like", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressNotLike(String value) {
            addCriterion("email_address not like", value, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressIn(List<String> values) {
            addCriterion("email_address in", values, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressNotIn(List<String> values) {
            addCriterion("email_address not in", values, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressBetween(String value1, String value2) {
            addCriterion("email_address between", value1, value2, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailAddressNotBetween(String value1, String value2) {
            addCriterion("email_address not between", value1, value2, "emailAddress");
            return (Criteria) this;
        }

        public Criteria andEmailPasswordIsNull() {
            addCriterion("email_password is null");
            return (Criteria) this;
        }

        public Criteria andEmailPasswordIsNotNull() {
            addCriterion("email_password is not null");
            return (Criteria) this;
        }

        public Criteria andEmailPasswordEqualTo(String value) {
            addCriterion("email_password =", value, "emailPassword");
            return (Criteria) this;
        }

        public Criteria andEmailPasswordNotEqualTo(String value) {
            addCriterion("email_password <>", value, "emailPassword");
            return (Criteria) this;
        }

        public Criteria andEmailPasswordGreaterThan(String value) {
            addCriterion("email_password >", value, "emailPassword");
            return (Criteria) this;
        }

        public Criteria andEmailPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("email_password >=", value, "emailPassword");
            return (Criteria) this;
        }

        public Criteria andEmailPasswordLessThan(String value) {
            addCriterion("email_password <", value, "emailPassword");
            return (Criteria) this;
        }

        public Criteria andEmailPasswordLessThanOrEqualTo(String value) {
            addCriterion("email_password <=", value, "emailPassword");
            return (Criteria) this;
        }

        public Criteria andEmailPasswordLike(String value) {
            addCriterion("email_password like", value, "emailPassword");
            return (Criteria) this;
        }

        public Criteria andEmailPasswordNotLike(String value) {
            addCriterion("email_password not like", value, "emailPassword");
            return (Criteria) this;
        }

        public Criteria andEmailPasswordIn(List<String> values) {
            addCriterion("email_password in", values, "emailPassword");
            return (Criteria) this;
        }

        public Criteria andEmailPasswordNotIn(List<String> values) {
            addCriterion("email_password not in", values, "emailPassword");
            return (Criteria) this;
        }

        public Criteria andEmailPasswordBetween(String value1, String value2) {
            addCriterion("email_password between", value1, value2, "emailPassword");
            return (Criteria) this;
        }

        public Criteria andEmailPasswordNotBetween(String value1, String value2) {
            addCriterion("email_password not between", value1, value2, "emailPassword");
            return (Criteria) this;
        }

        public Criteria andReceiveProtocolIsNull() {
            addCriterion("receive_protocol is null");
            return (Criteria) this;
        }

        public Criteria andReceiveProtocolIsNotNull() {
            addCriterion("receive_protocol is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveProtocolEqualTo(String value) {
            addCriterion("receive_protocol =", value, "receiveProtocol");
            return (Criteria) this;
        }

        public Criteria andReceiveProtocolNotEqualTo(String value) {
            addCriterion("receive_protocol <>", value, "receiveProtocol");
            return (Criteria) this;
        }

        public Criteria andReceiveProtocolGreaterThan(String value) {
            addCriterion("receive_protocol >", value, "receiveProtocol");
            return (Criteria) this;
        }

        public Criteria andReceiveProtocolGreaterThanOrEqualTo(String value) {
            addCriterion("receive_protocol >=", value, "receiveProtocol");
            return (Criteria) this;
        }

        public Criteria andReceiveProtocolLessThan(String value) {
            addCriterion("receive_protocol <", value, "receiveProtocol");
            return (Criteria) this;
        }

        public Criteria andReceiveProtocolLessThanOrEqualTo(String value) {
            addCriterion("receive_protocol <=", value, "receiveProtocol");
            return (Criteria) this;
        }

        public Criteria andReceiveProtocolLike(String value) {
            addCriterion("receive_protocol like", value, "receiveProtocol");
            return (Criteria) this;
        }

        public Criteria andReceiveProtocolNotLike(String value) {
            addCriterion("receive_protocol not like", value, "receiveProtocol");
            return (Criteria) this;
        }

        public Criteria andReceiveProtocolIn(List<String> values) {
            addCriterion("receive_protocol in", values, "receiveProtocol");
            return (Criteria) this;
        }

        public Criteria andReceiveProtocolNotIn(List<String> values) {
            addCriterion("receive_protocol not in", values, "receiveProtocol");
            return (Criteria) this;
        }

        public Criteria andReceiveProtocolBetween(String value1, String value2) {
            addCriterion("receive_protocol between", value1, value2, "receiveProtocol");
            return (Criteria) this;
        }

        public Criteria andReceiveProtocolNotBetween(String value1, String value2) {
            addCriterion("receive_protocol not between", value1, value2, "receiveProtocol");
            return (Criteria) this;
        }

        public Criteria andReceivePortIsNull() {
            addCriterion("receive_port is null");
            return (Criteria) this;
        }

        public Criteria andReceivePortIsNotNull() {
            addCriterion("receive_port is not null");
            return (Criteria) this;
        }

        public Criteria andReceivePortEqualTo(String value) {
            addCriterion("receive_port =", value, "receivePort");
            return (Criteria) this;
        }

        public Criteria andReceivePortNotEqualTo(String value) {
            addCriterion("receive_port <>", value, "receivePort");
            return (Criteria) this;
        }

        public Criteria andReceivePortGreaterThan(String value) {
            addCriterion("receive_port >", value, "receivePort");
            return (Criteria) this;
        }

        public Criteria andReceivePortGreaterThanOrEqualTo(String value) {
            addCriterion("receive_port >=", value, "receivePort");
            return (Criteria) this;
        }

        public Criteria andReceivePortLessThan(String value) {
            addCriterion("receive_port <", value, "receivePort");
            return (Criteria) this;
        }

        public Criteria andReceivePortLessThanOrEqualTo(String value) {
            addCriterion("receive_port <=", value, "receivePort");
            return (Criteria) this;
        }

        public Criteria andReceivePortLike(String value) {
            addCriterion("receive_port like", value, "receivePort");
            return (Criteria) this;
        }

        public Criteria andReceivePortNotLike(String value) {
            addCriterion("receive_port not like", value, "receivePort");
            return (Criteria) this;
        }

        public Criteria andReceivePortIn(List<String> values) {
            addCriterion("receive_port in", values, "receivePort");
            return (Criteria) this;
        }

        public Criteria andReceivePortNotIn(List<String> values) {
            addCriterion("receive_port not in", values, "receivePort");
            return (Criteria) this;
        }

        public Criteria andReceivePortBetween(String value1, String value2) {
            addCriterion("receive_port between", value1, value2, "receivePort");
            return (Criteria) this;
        }

        public Criteria andReceivePortNotBetween(String value1, String value2) {
            addCriterion("receive_port not between", value1, value2, "receivePort");
            return (Criteria) this;
        }

        public Criteria andReceiveHostIsNull() {
            addCriterion("receive_host is null");
            return (Criteria) this;
        }

        public Criteria andReceiveHostIsNotNull() {
            addCriterion("receive_host is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveHostEqualTo(String value) {
            addCriterion("receive_host =", value, "receiveHost");
            return (Criteria) this;
        }

        public Criteria andReceiveHostNotEqualTo(String value) {
            addCriterion("receive_host <>", value, "receiveHost");
            return (Criteria) this;
        }

        public Criteria andReceiveHostGreaterThan(String value) {
            addCriterion("receive_host >", value, "receiveHost");
            return (Criteria) this;
        }

        public Criteria andReceiveHostGreaterThanOrEqualTo(String value) {
            addCriterion("receive_host >=", value, "receiveHost");
            return (Criteria) this;
        }

        public Criteria andReceiveHostLessThan(String value) {
            addCriterion("receive_host <", value, "receiveHost");
            return (Criteria) this;
        }

        public Criteria andReceiveHostLessThanOrEqualTo(String value) {
            addCriterion("receive_host <=", value, "receiveHost");
            return (Criteria) this;
        }

        public Criteria andReceiveHostLike(String value) {
            addCriterion("receive_host like", value, "receiveHost");
            return (Criteria) this;
        }

        public Criteria andReceiveHostNotLike(String value) {
            addCriterion("receive_host not like", value, "receiveHost");
            return (Criteria) this;
        }

        public Criteria andReceiveHostIn(List<String> values) {
            addCriterion("receive_host in", values, "receiveHost");
            return (Criteria) this;
        }

        public Criteria andReceiveHostNotIn(List<String> values) {
            addCriterion("receive_host not in", values, "receiveHost");
            return (Criteria) this;
        }

        public Criteria andReceiveHostBetween(String value1, String value2) {
            addCriterion("receive_host between", value1, value2, "receiveHost");
            return (Criteria) this;
        }

        public Criteria andReceiveHostNotBetween(String value1, String value2) {
            addCriterion("receive_host not between", value1, value2, "receiveHost");
            return (Criteria) this;
        }

        public Criteria andEmailStateIsNull() {
            addCriterion("email_state is null");
            return (Criteria) this;
        }

        public Criteria andEmailStateIsNotNull() {
            addCriterion("email_state is not null");
            return (Criteria) this;
        }

        public Criteria andEmailStateEqualTo(Boolean value) {
            addCriterion("email_state =", value, "emailState");
            return (Criteria) this;
        }

        public Criteria andEmailStateNotEqualTo(Boolean value) {
            addCriterion("email_state <>", value, "emailState");
            return (Criteria) this;
        }

        public Criteria andEmailStateGreaterThan(Boolean value) {
            addCriterion("email_state >", value, "emailState");
            return (Criteria) this;
        }

        public Criteria andEmailStateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("email_state >=", value, "emailState");
            return (Criteria) this;
        }

        public Criteria andEmailStateLessThan(Boolean value) {
            addCriterion("email_state <", value, "emailState");
            return (Criteria) this;
        }

        public Criteria andEmailStateLessThanOrEqualTo(Boolean value) {
            addCriterion("email_state <=", value, "emailState");
            return (Criteria) this;
        }

        public Criteria andEmailStateIn(List<Boolean> values) {
            addCriterion("email_state in", values, "emailState");
            return (Criteria) this;
        }

        public Criteria andEmailStateNotIn(List<Boolean> values) {
            addCriterion("email_state not in", values, "emailState");
            return (Criteria) this;
        }

        public Criteria andEmailStateBetween(Boolean value1, Boolean value2) {
            addCriterion("email_state between", value1, value2, "emailState");
            return (Criteria) this;
        }

        public Criteria andEmailStateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("email_state not between", value1, value2, "emailState");
            return (Criteria) this;
        }

        public Criteria andSendHostIsNull() {
            addCriterion("send_host is null");
            return (Criteria) this;
        }

        public Criteria andSendHostIsNotNull() {
            addCriterion("send_host is not null");
            return (Criteria) this;
        }

        public Criteria andSendHostEqualTo(String value) {
            addCriterion("send_host =", value, "sendHost");
            return (Criteria) this;
        }

        public Criteria andSendHostNotEqualTo(String value) {
            addCriterion("send_host <>", value, "sendHost");
            return (Criteria) this;
        }

        public Criteria andSendHostGreaterThan(String value) {
            addCriterion("send_host >", value, "sendHost");
            return (Criteria) this;
        }

        public Criteria andSendHostGreaterThanOrEqualTo(String value) {
            addCriterion("send_host >=", value, "sendHost");
            return (Criteria) this;
        }

        public Criteria andSendHostLessThan(String value) {
            addCriterion("send_host <", value, "sendHost");
            return (Criteria) this;
        }

        public Criteria andSendHostLessThanOrEqualTo(String value) {
            addCriterion("send_host <=", value, "sendHost");
            return (Criteria) this;
        }

        public Criteria andSendHostLike(String value) {
            addCriterion("send_host like", value, "sendHost");
            return (Criteria) this;
        }

        public Criteria andSendHostNotLike(String value) {
            addCriterion("send_host not like", value, "sendHost");
            return (Criteria) this;
        }

        public Criteria andSendHostIn(List<String> values) {
            addCriterion("send_host in", values, "sendHost");
            return (Criteria) this;
        }

        public Criteria andSendHostNotIn(List<String> values) {
            addCriterion("send_host not in", values, "sendHost");
            return (Criteria) this;
        }

        public Criteria andSendHostBetween(String value1, String value2) {
            addCriterion("send_host between", value1, value2, "sendHost");
            return (Criteria) this;
        }

        public Criteria andSendHostNotBetween(String value1, String value2) {
            addCriterion("send_host not between", value1, value2, "sendHost");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_email_account
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}