package com.lxc.myemail.model;

import lombok.ToString;

import java.io.Serializable;

@ToString
public class EmailAccount implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email_account.email_id
     *
     * @mbg.generated
     */
    private Integer emailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email_account.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email_account.email_address
     *
     * @mbg.generated
     */
    private String emailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email_account.email_password
     *
     * @mbg.generated
     */
    private String emailPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email_account.receive_protocol
     *
     * @mbg.generated
     */
    private String receiveProtocol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email_account.receive_port
     *
     * @mbg.generated
     */
    private String receivePort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email_account.receive_host
     *
     * @mbg.generated
     */
    private String receiveHost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email_account.email_state
     *
     * @mbg.generated
     */
    private Boolean emailState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email_account.send_host
     *
     * @mbg.generated
     */
    private String sendHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_email_account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email_account.email_id
     *
     * @return the value of t_email_account.email_id
     *
     * @mbg.generated
     */
    public Integer getEmailId() {
        return emailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email_account.email_id
     *
     * @param emailId the value for t_email_account.email_id
     *
     * @mbg.generated
     */
    public void setEmailId(Integer emailId) {
        this.emailId = emailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email_account.user_id
     *
     * @return the value of t_email_account.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email_account.user_id
     *
     * @param userId the value for t_email_account.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email_account.email_address
     *
     * @return the value of t_email_account.email_address
     *
     * @mbg.generated
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email_account.email_address
     *
     * @param emailAddress the value for t_email_account.email_address
     *
     * @mbg.generated
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress == null ? null : emailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email_account.email_password
     *
     * @return the value of t_email_account.email_password
     *
     * @mbg.generated
     */
    public String getEmailPassword() {
        return emailPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email_account.email_password
     *
     * @param emailPassword the value for t_email_account.email_password
     *
     * @mbg.generated
     */
    public void setEmailPassword(String emailPassword) {
        this.emailPassword = emailPassword == null ? null : emailPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email_account.receive_protocol
     *
     * @return the value of t_email_account.receive_protocol
     *
     * @mbg.generated
     */
    public String getReceiveProtocol() {
        return receiveProtocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email_account.receive_protocol
     *
     * @param receiveProtocol the value for t_email_account.receive_protocol
     *
     * @mbg.generated
     */
    public void setReceiveProtocol(String receiveProtocol) {
        this.receiveProtocol = receiveProtocol == null ? null : receiveProtocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email_account.receive_port
     *
     * @return the value of t_email_account.receive_port
     *
     * @mbg.generated
     */
    public String getReceivePort() {
        return receivePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email_account.receive_port
     *
     * @param receivePort the value for t_email_account.receive_port
     *
     * @mbg.generated
     */
    public void setReceivePort(String receivePort) {
        this.receivePort = receivePort == null ? null : receivePort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email_account.receive_host
     *
     * @return the value of t_email_account.receive_host
     *
     * @mbg.generated
     */
    public String getReceiveHost() {
        return receiveHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email_account.receive_host
     *
     * @param receiveHost the value for t_email_account.receive_host
     *
     * @mbg.generated
     */
    public void setReceiveHost(String receiveHost) {
        this.receiveHost = receiveHost == null ? null : receiveHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email_account.email_state
     *
     * @return the value of t_email_account.email_state
     *
     * @mbg.generated
     */
    public Boolean getEmailState() {
        return emailState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email_account.email_state
     *
     * @param emailState the value for t_email_account.email_state
     *
     * @mbg.generated
     */
    public void setEmailState(Boolean emailState) {
        this.emailState = emailState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email_account.send_host
     *
     * @return the value of t_email_account.send_host
     *
     * @mbg.generated
     */
    public String getSendHost() {
        return sendHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email_account.send_host
     *
     * @param sendHost the value for t_email_account.send_host
     *
     * @mbg.generated
     */
    public void setSendHost(String sendHost) {
        this.sendHost = sendHost == null ? null : sendHost.trim();
    }


}